server:
    port: 8091
    session-timeout: 30000
    tomcat:
        uri-encoding: UTF-8
        
#eureka:
#    instance:
#        prefer-ip-address: true
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
#        register-with-eureka: true
#        fetch-registry: true
#        registry-fetch-interval-seconds: 30
#    server:
#        eviction-interval-timer-in-ms: 3000

spring:
    application:
        name: mbp-video
    datasource:
        platform: mysql
        url: jdbc:mysql://127.0.0.1:13306/mybatis_plus_demo?characterEncoding=utf8
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        max-active: 50
        max-idle: 30
        min-idle: 2
        initial-size: 30
        
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wondertek.oes.content.entity
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 1
    OkToRetryOnAllOperations: false

feign:
    httpclient:
        enabled: false
    
    okhttp:
        enabled: true
    
    client:
        config:
            default:
                connectTimeout: 60000
                readTimeout: 60000
                loggerLevel: basic

oes:
    log:
        level: INFO
        open_console: true

#Apollo config
#app:
#    id: mbp-video
#
#apollo:
#    bootstrap:
#        enabled: true
#        eagerLoad:
#            enabled: true
#    meta: http://localhost:8080
